export const SEND_LOGIN_OTP_REQUEST = "SEND_LOGIN_OTP_REQUEST";
export const SEND_LOGIN_OTP_SUCCESS = "SEND_LOGIN_OTP_SUCCESS";
export const SEND_LOGIN_OTP_FAIL = "SEND_LOGIN_OTP_FAIL";


export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAIL = "GET_LOGIN_FAIL";

export const GET_USERSELF_REQUEST = "GET_USERSELF_REQUEST";
export const GET_USERSELF_SUCCESS = "GET_USERSELF_SUCCESS";
export const GET_USERSELF_FAILURE = "GET_USERSELF_FAILURE";

export const GET_FRESH_SIGNUP_OTP_REQUEST = "GET_FRESH_SIGNUP_OTP_REQUEST";
export const GET_FRESH_SIGNUP_OTP_SUCCESS = "GET_FRESH_SIGNUP_OTP_SUCCESS";
export const GET_FRESH_SIGNUP_OTP_FAILURE = "GET_FRESH_SIGNUP_OTP_FAILURE";

export const GET_FRESH_SIGNUP_REQUEST = "GET_FRESH_SIGNUP_REQUEST";
export const GET_FRESH_SIGNUP_SUCCESS = "GET_FRESH_SIGNUP_SUCCESS";
export const GET_FRESH_SIGNUP_FAILURE = "GET_FRESH_SIGNUP_FAILURE";

