export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';


export const GET_POST_COMMENT_REQUEST = 'GET_POST_COMMENT_REQUEST';
export const GET_POST_COMMENT_SUCCESS = 'GET_POST_COMMENT_SUCCESS';
export const GET_POST_COMMENT_FAILURE = 'GET_POST_COMMENT_FAILURE';


export const ADD_REPLY_REQUEST = 'ADD_REPLY_REQUEST';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_FAILURE = 'ADD_REPLY_FAILURE';


export const GET_REPLY_REQUEST = 'GET_REPLY_REQUEST';
export const GET_REPLY_SUCCESS = 'GET_REPLY_SUCCESS';
export const GET_REPLY_FAILURE = 'GET_REPLY_FAILURE';