export const IS_USERNAME_AVIALABLE_REQUEST = 'IS_USERNAME_AVIALABLE_REQUEST';
export const IS_USERNAME_AVIALABLE_SUCCESS = 'IS_USERNAME_AVIALABLE_SUCCESS';
export const IS_USERNAME_AVIALABLE_FAILURE = 'IS_USERNAME_AVIALABLE_FAILURE';

export const IS_USERNAME_DONE_REQUEST = 'IS_USERNAME_DONE_REQUEST';
export const IS_USERNAME_DONE_SUCCESS = 'IS_USERNAME_DONE_SUCCESS';
export const IS_USERNAME_DONE_FAILURE = 'IS_USERNAME_DONE_FAILURE';

export const OBJECT_EDIT_REQUEST = "OBJECT_EDIT_REQUEST";
export const OBJECT_EDIT_SUCCESS = "OBJECT_EDIT_SUCCESS";
export const OBJECT_EDIT_FAILURE = "OBJECT_EDIT_FAILURE";