export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST';
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POST_FAILURE';

export const GIVE_POST_LIKE_REQUEST = 'GIVE_POST_LIKE';
export const GIVE_POST_LIKE_SUCCESS = 'GIVE_POST_LIKE_SUCCESS';
export const GIVE_POST_LIKE_FAILURE = 'GIVE_POST_LIKE_FAILURE';