export const GET_USER_BY_NAME_REQUEST = 'GET_USER_BY_NAME_REQUEST';
export const GET_USER_BY_NAME_SUCCESS = 'GET_USER_BY_NAME_SUCCESS';
export const GET_USER_BY_NAME_FAILURE = 'GET_USER_BY_NAME_FAILURE';

export const GET_SKILLED_USER_REQUEST = 'GET_SKILLED_USER_REQUEST';
export const GET_SKILLED_USER_SUCCESS = 'GET_SKILLED_USER_SUCCESS';
export const GET_SKILLED_USER_FAILURE = 'GET_SKILLED_USER_FAILURE';
