export const GET_USER_BY_NAME_REQUEST = 'GET_USER_BY_NAME_REQUEST';
export const GET_USER_BY_NAME_SUCCESS = 'GET_USER_BY_NAME_SUCCESS';
export const GET_USER_BY_NAME_FAILURE = 'GET_USER_BY_NAME_FAILURE';
