export const LOAD_USER_PROFILE_REQUEST = 'LOAD_USER_PROFILE_REQUEST';
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAILURE = 'LOAD_USER_PROFILE_FAILURE';

export const EDIT_DP_REQUEST = "EDIT_DP_REQUEST";
export const EDIT_DP_SUCCESS = "EDIT_DP_SUCCESS";
export const EDIT_DP_FAILURE = "EDIT_DP_FAILURE";

export const GET_USER_FOLLOWERS_REQUEST =  "GET_USER_FOLLOWERS_REQUEST";
export const GET_USER_FOLLOWERS_SUCCESS = "GET_USER_FOLLOWERS_SUCCESS";
export const GET_USER_FOLLOWERS_FAILURE = "GET_USER_FOLLOWERS_FAILURE";


export const GET_USER_FOLLOWING_REQUEST =  "GET_USER_FOLLOWING_REQUEST";
export const GET_USER_FOLLOWING_SUCCESS = "GET_USER_FOLLOWING_SUCCESS";
export const GET_USER_FOLLOWING_FAILURE = "GET_USER_FOLLOWING_FAILURE";