export const LOAD_USER_PROFILE_REQUEST = 'LOAD_USER_PROFILE_REQUEST';
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAILURE = 'LOAD_USER_PROFILE_FAILURE';

export const EDIT_DP_REQUEST = "EDIT_DP_REQUEST";
export const EDIT_DP_SUCCESS = "EDIT_DP_SUCCESS";
export const EDIT_DP_FAILURE = "EDIT_DP_FAILURE";